[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."download-folder"]
  timeout = 26

[functions."cron_jobs_HAYS-background"]
  external_node_modules = ["playwright-core", "playwright", "@sparticuz/chromium"]
  included_files = ["node_modules/@sparticuz/chromium/**"]

[build.environment]
  NODE_VERSION = "20"
